### PR TITLE
Retry when GetMetadataFromChain fails

### LINKED ISSUE #1254: Relayer panicked when dym rpc went down and never came back
`    * Feb 07 06:05:29 b-ah3 roller[719890]:   ERROR   failed to fetch rollapp information from hub:  command execution failed: exit status 1, stderr: Error: post failed: Post "https://dymension-mainnet-tendermint.public.blastapi.io:443": dial tcp: lookup dymension-mainnet-tendermint.public.blastapi.io on 127.0.0.53:53: read udp 127.0.0.1:39414->127.0.0.53:53: read: connection 
`

### PR DESCRIPTION
**Pull request by anhductn2001**
Close #1254 #1249 
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case PR targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: cmd/relayer/status/status.go [hunk 1]
```diff
@@ -41,6 +42,13 @@ func Cmd() *cobra.Command {
 			raData := rlyCfg.RaDataFromRelayerConfig()
 			hd := rlyCfg.HubDataFromRelayerConfig()
 
+			_, err = rollapp.GetMetadataFromChain(raData.ID, *hd)
+			if err != nil {
+				pterm.Error.Println("failed to fetch rollapp information from hub: ", err)
+				pterm.Error.Println("the hub rpc endpoint is not responsive")
```
Comment (artemijspavlovs) [inline cmd/relayer/status/status.go:48]: this might not be the case, if we want to explicitly return an error type that's along the lines of "endpoint unavailable" and check whether the returned error is of this type with `errors.Is`

I think returning the failed to fetch error is enough as there are outputs statin unhealthy endpoint in the retry loop already

**Review by artemijspavlovs — APPROVED** [review]
