### PR TITLE
fix: mock

### LINKED ISSUE #1325: fix mock on roller

### PR DESCRIPTION
**Pull request by anhductn2001**
Close #1325 
# PR Standards

## Opening a pull request should be able to meet the following requirements

---

For Author:

- [ ]  Targeted PR against correct branch
- [ ]  Included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to Github issue with discussion and accepted design
- [ ]  Targets only one github issue
- [ ]  Wrote unit and integration tests
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)

---

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---

After reviewer approval:

- [ ]  In case PR targets main branch, PR should be squashed and merged.
- [ ]  In case PR targets a release branch, PR should be rebased.

### CODE REVIEW

File: cmd/rollapp/init/init.go [hunk 1]
```diff
@@ -31,14 +31,20 @@ func Cmd() *cobra.Command {
...
-			)
-			pterm.Info.Printf(
-				"run %s to update the Hub private endpoints anytime after initial setup\n",
-				pterm.DefaultBasicText.WithStyle(pterm.FgYellow.ToStyle()).
-					Sprintf("roller config set hub-rpc-endpoint <private-endpoint>"),
-			)
+			shouldUseMockBackend, _ := cmd.Flags().GetBool("mock")
+			shouldSkipBinaryInstallation, _ := cmd.Flags().GetBool("skip-binary-installation")
+
+			if !shouldUseMockBackend {
```
Comment (artemijspavlovs) [inline cmd/rollapp/init/init.go:37]: this prompt should show up only for mainnet

**Review by artemijspavlovs — APPROVED** [review]
